/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments/index'
import { Route as QuizAssessmentIdRouteImport } from './routes/quiz/$assessmentId'
import { Route as ResultsSessionIdAssessmentIdRouteImport } from './routes/results/$sessionId.$assessmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizAssessmentIdRoute = QuizAssessmentIdRouteImport.update({
  id: '/quiz/$assessmentId',
  path: '/quiz/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSessionIdAssessmentIdRoute =
  ResultsSessionIdAssessmentIdRouteImport.update({
    id: '/results/$sessionId/$assessmentId',
    path: '/results/$sessionId/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz/$assessmentId': typeof QuizAssessmentIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/results/$sessionId/$assessmentId': typeof ResultsSessionIdAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz/$assessmentId': typeof QuizAssessmentIdRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/results/$sessionId/$assessmentId': typeof ResultsSessionIdAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz/$assessmentId': typeof QuizAssessmentIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/results/$sessionId/$assessmentId': typeof ResultsSessionIdAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz/$assessmentId'
    | '/assessments/'
    | '/results/$sessionId/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quiz/$assessmentId'
    | '/assessments'
    | '/results/$sessionId/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/quiz/$assessmentId'
    | '/assessments/'
    | '/results/$sessionId/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizAssessmentIdRoute: typeof QuizAssessmentIdRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  ResultsSessionIdAssessmentIdRoute: typeof ResultsSessionIdAssessmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$assessmentId': {
      id: '/quiz/$assessmentId'
      path: '/quiz/$assessmentId'
      fullPath: '/quiz/$assessmentId'
      preLoaderRoute: typeof QuizAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$sessionId/$assessmentId': {
      id: '/results/$sessionId/$assessmentId'
      path: '/results/$sessionId/$assessmentId'
      fullPath: '/results/$sessionId/$assessmentId'
      preLoaderRoute: typeof ResultsSessionIdAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizAssessmentIdRoute: QuizAssessmentIdRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  ResultsSessionIdAssessmentIdRoute: ResultsSessionIdAssessmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
